# fly.toml app configuration file generated for radio-proxy on 2025-05-20T07:18:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "radio-proxy-zuniga"
primary_region = "iad"

[build]

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
